name: CI/CD workflow for Maven Build and Sonar Code scan
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
   
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: /web/modules
        args: >
          -Dsonar.projectKey=ayush-drupal
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
