name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonarqube_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          sonar-host-url: http://localhost:9000
          sonar-login: ${{ secrets.SONAR_TOKEN }}
          sonar-project-key: ayush-drupal
          sonar-sources: web/modules/  # Adjust path to your Drupal module directory
          
      - name: Upload SonarQube results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: sonarqube-report
          path: .scannerwork/report-task.txt
